
CREATE TABLE logfile(
	Id							  INT(11) NOT NULL AUTO_INCREMENT
	,lf_Offset                    VARCHAR(18)
	,lf_MFTReference              BIGINT
	,lf_RealMFTReference          BIGINT 
	,lf_MFTBaseRecRef             BIGINT 
	,lf_LSN                       BIGINT
	,lf_LSNPrevious               BIGINT
	,lf_RedoOperation             VARCHAR(32)
	,lf_UndoOperation             VARCHAR(32)
	,lf_OffsetInMft               INTEGER
	,lf_FileName                  VARCHAR(255)
	,lf_CurrentAttribute          VARCHAR(128)
	,lf_TextInformation           MEDIUMTEXT
	,lf_UsnJrnlFileName           VARCHAR(255)
	,lf_UsnJrnlMFTReference       BIGINT 
	,lf_UsnJrnlMFTParentReference BIGINT 
	,lf_UsnJrnlTimestamp          DATETIME(6) 
	,lf_UsnJrnlReason             VARCHAR(128)
	,lf_UsnJrnlUsn                BIGINT 
	,lf_SI_CTime                  DATETIME(6) 
	,lf_SI_ATime                  DATETIME(6) 
	,lf_SI_MTime                  DATETIME(6) 
	,lf_SI_RTime                  DATETIME(6) 
	,lf_SI_FilePermission         VARCHAR(255)
	,lf_SI_MaxVersions            INTEGER 
	,lf_SI_VersionNumber          INTEGER 
	,lf_SI_ClassID                INTEGER 
	,lf_SI_SecurityID             INTEGER 
	,lf_SI_QuotaCharged           BIGINT 
	,lf_SI_USN                    BIGINT 
	,lf_SI_PartialValue           VARCHAR(32)
	,lf_FN_CTime                  DATETIME(6) 
	,lf_FN_ATime                  DATETIME(6) 
	,lf_FN_MTime                  DATETIME(6) 
	,lf_FN_RTime                  DATETIME(6) 
	,lf_FN_AllocSize              BIGINT 
	,lf_FN_RealSize               BIGINT 
	,lf_FN_Flags                  VARCHAR(64)
	,lf_FN_Namespace              VARCHAR(9)
	,lf_DT_StartVCN               BIGINT 
	,lf_DT_LastVCN                BIGINT 
	,lf_DT_ComprUnitSize          INTEGER 
	,lf_DT_AllocSize              BIGINT 
	,lf_DT_RealSize               BIGINT 
	,lf_DT_InitStreamSize         BIGINT 
	,lf_DT_DataRuns               MEDIUMTEXT
	,lf_DT_Name                   VARCHAR(255)
	,lf_FileNameModified          VARCHAR(255)
	,lf_RedoChunkSize             INTEGER
	,lf_UndoChunkSize             INTEGER
	,lf_client_index              VARCHAR(10)
	,lf_record_type               INTEGER
	,lf_transaction_id            VARCHAR(10)
	,lf_flags                     VARCHAR(6)
	,lf_target_attribute          VARCHAR(6)
	,lf_lcns_to_follow            VARCHAR(6)
	,lf_attribute_offset          INTEGER
	,lf_MftClusterIndex           VARCHAR(6)
	,lf_target_vcn                VARCHAR(10)
	,lf_target_lcn                VARCHAR(10)
	,InOpenAttributeTable         BIGINT
	,FromRcrdSlack                INTEGER
	,IncompleteTransaction        TINYINT(1)
	,PRIMARY KEY (Id)
);
